- name: gnome | appearance | copy lock screen and wallpaper background files
  tags: gnome,gnome-lockscreen
  with_items:
    - { src: files/gnome/wallpaper.png, dest: "/usr/share/backgrounds/default-wallpaper.png" }
    - { src: files/gnome/lockscreen.png, dest: "/usr/share/backgrounds/default-lockscreen.png" }
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ username }}"
    group: wheel
    mode: 0644

- name: gnome | configure defaults gnome shell
  tags: gnome,
  become_user: "{{ username }}"
  dconf:
    key: "{{ item.key }}"
    value: "{{ item.value }}"
  with_items:
    - { key: "/org/gnome/desktop/screensaver/picture-uri", value: "'file:///usr/share/backgrounds/default-lockscreen.png'" }
    - { key: "/org/gnome/desktop/background/picture-uri", value: "'file:///usr/share/backgrounds/default-wallpaper.png'" }
    - { key: "/org/gnome/desktop/background/picture-options", value: "'zoom'" }
    - { key: "/org/gnome/tweaks/show-extensions-notice", value: "'false'" }
    - { key: "/org/gnome/desktop/calendar/show-weekdate", value: "'true'" }
    - { key: "/org/gnome/desktop/datetime/automatic-timezone", value: "'true'" }
    - { key: "/org/gnome/desktop/interface/clock-show-date", value: "'true'" }
    - { key: "/org/gnome/desktop/interface/cursor-size", value: "'48'" }
    - { key: "/org/gnome/desktop/interface/text-scaling-factor", value: "'1/25'" }
    - { key: "/org/gnome/desktop/peripherals/touchpad/tap-to-click", value: "'true'" }
    - { key: "/org/gnome/desktop/privacy/old-files-age", value: "uint32 5" }
    - { key: "/org/gnome/desktop/privacy/remember-app-usage", value: "'false'" }
    - { key: "/org/gnome/desktop/privacy/remember-recent-files", value: "'false'" }
    - { key: "/org/gnome/desktop/privacy/remove-old-temp-files", value: "'true'" }
    - { key: "/org/gnome/desktop/privacy/remove-old-trash-files", value: "'true'" }
    - { key: "/org/gnome/desktop/privacy/show-full-name-in-top-bar", value: "'false'" }
    - { key: "/org/gnome/desktop/wm/preferences/button-layout", value: "':minimize,maximize,close'" }
    - { key: "/org/gnome/settings-daemon/plugins/color/night-light-enabled", value: "'false'" }
    - { key: "/org/gnome/settings-daemon/plugins/power/sleep-inactive-ac-timeout", value: "'3600'" }
    - { key: "/org/gnome/settings-daemon/plugins/power/sleep-inactive-ac-type", value: "'nothing'" }
    - { key: "/org/gnome/settings-daemon/plugins/power/sleep-inactive-battery-timeout", value: "'1800'" }
    - { key: "/org/gnome/shell/app-switcher/current-workspace-only", value: "'true'" }
    - { key: "/org/gnome/shell/extensions/dash-to-panel/location-clock", value: "'STATUSRIGHT'" }
    - { key: "/org/gnome/software/refresh-when-metered", value: "'true'" }
    - { key: "/org/gnome/software/first-run", value: "'false'" }
    - { key: "/org/gnome/boxes/first-run", value: "'false'" }
    - { key: "/org/gnome/Terminal/Legacy/Settings/theme-variant", value: "'dark'" }
    - { key: "/org/gnome/swell-foop/first-run", value: "'false'" }
    - { key: "/org/gnome/nibbles/first-run", value: "'false'" }
    - { key: "/org/gnome/todo/first-run", value: "'false'" }
    - { key: "/org/gnome/desktop/sound/allow-volume-above-100-percent", value: "'true'" }
    - { key: "/org/gnome/shell/extensions/dash-to-panel/show-show-apps-button", value: "'false'" }
    - { key: "/org/gtk/Settings/FileChooser/sort-directories-first", value: "'true'" }
    - { key: "/org/gnome/shell/favorite-apps", value: "['org.gnome.Evolution.desktop', 'libreoffice-writer.desktop', 'org.gnome.Nautilus.desktop', 'org.gnome.Software.desktop', 'org.gnome.Terminal.desktop', 'firefox-esr.desktop']" }
    - { key: "/org/gnome/shell/enabled-extensions", value: "{{ gnome_enable_extensions|default([]) }}" }
